### ISSUE TITLE
Does it works for Ender 5 - Pro?

### ISSUE THREAD

**Issue by gvmturl** [cesarvandevelde/OctoPrint-M73Progress#11]
Does it works for Ender 5 - Pro? If not is there anyway to remix it?

Thank you!

**Comment by cesarvandevelde** [comment]
No idea. Try sending the g-code command `M73 P25` via the terminal tab in OctoPrint. If the progress bar updates to 25%, the plugin will work.

**Comment by gvmturl** [comment]
Not working! is there anyway to adapt it?

Thank you!!!

**Comment by cesarvandevelde** [comment]
You'd have to switch to a different firmware (e.g. Marlin). That's outside of the scope of this project, though. :)
