### ISSUE TITLE
Manual M73 command works but no progress during print

### ISSUE THREAD

**Issue by bobbanks** [cesarvandevelde/OctoPrint-M73Progress#3]
Is any GCODE needed at the start of print?  I've confirmed LCD_SET_PROGRESS_MANUALLY is defined by manually setting the progress bar with an M73 in Terminal.  When printing from .gcode uploaded from Cura 3.10, progress bar doesn't update at all.

**Comment by bobbanks** [comment]
Looks like a server restart solved the problem.

**Comment by cesarvandevelde** [comment]
Good to know! I'll do some experimenting to see if I can reproduce this behavior. If so, I'll add the `RestartNeedingPlugin` mixin to the plugin. That should then resolve the issue for everyone.

**Comment by benlye** [comment]
Note that there is also an issue in the latest/current Marlin 2.0.x  where `P` parameters are silently ignored...
https://github.com/MarlinFirmware/Marlin/pull/9393
https://github.com/MarlinFirmware/Marlin/issues/9366

**Comment by bobbanks** [comment]
Thanks guys.  This was on a build of 1.1.8.
