### ISSUE TITLE
M73Progress not updating LCD with OctoPrint 1.3.8

### ISSUE THREAD

**Issue by b-morgan** [cesarvandevelde/OctoPrint-M73Progress#5]
This plugin was working for me with (I believe) OctoPrint 1.3.6. It currently isn't working with 1.3.8.

M78 P50 does move the bar to halfway.

**Comment by cesarvandevelde** [comment]
Hi Brad. I did a quick test on my system with v1.3.8 and everything is working as it should. Given the short and trivial nature of this plugin, it's unlikely to be an issue within M73Progress itself.

- Did you try rebooting your RPi after updating?
- Did you check your logs for M73Progress error messages?
